---
kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: node
  commands:
  - cd src/
  - npm install
  - npm test

trigger:
  branch:
  - master
  event:
  - cron
  - custom
  - push
  - pull_request
  - tag
  - promote
  - rollback